version: '3.9'

services:
  naijabiz:
    build: ./naijabiz
    container_name: naijabiz-backend
    networks:
      - app_network
    environment:
      - LOCAL_PORT=8000
      - LOCAL_DB_NAME=${DB_NAME}
      - LOCAL_USERNAME=${DB_USER}
      - LOCAL_HOSTNAME=${DB_HOST}
      - LOCAL_PASSWORD=${DB_PASSWORD}
      - DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - backend_db
      - redis
    command: >
      sh -c "
      python manage.py collectstatic --noinput  &&
      daphne -b 0.0.0.0 -p 8000 naijabiz.asgi:application
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media



  backend_db:
    image: postgres:14-alpine
    container_name: backend-db
    networks:
      - app_network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pos_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - naijabiz
    networks:
      - app_network
    ports:
      - "86:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app_network
    ports:
      - "6379:6379"
    restart: always

volumes:
  pos_data:
    driver: local
  static_volume:
  media_volume:

networks:
  app_network:
